/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as QuranClassesForNewMuslimsRouteImport } from './routes/quran-classes-for-new-muslims'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OnlineTajweedClassesRouteImport } from './routes/online-tajweed-classes'
import { Route as OnlineQuranRecitationClassesRouteImport } from './routes/online-quran-recitation-classes'
import { Route as OnlineQuranClassesUsaRouteImport } from './routes/online-quran-classes-usa'
import { Route as OnlineQuranClassesUkRouteImport } from './routes/online-quran-classes-uk'
import { Route as OnlineQuranClassesForKidsRouteImport } from './routes/online-quran-classes-for-kids'
import { Route as OnlineQuranClassesForAdultsRouteImport } from './routes/online-quran-classes-for-adults'
import { Route as OnlineQuranClassesCanadaRouteImport } from './routes/online-quran-classes-canada'
import { Route as OnlineQuranClassesAustraliaRouteImport } from './routes/online-quran-classes-australia'
import { Route as OnlineIslamicStudiesRouteImport } from './routes/online-islamic-studies'
import { Route as OnlineHifzClassesRouteImport } from './routes/online-hifz-classes'
import { Route as OnlineArabicLanguageClassesRouteImport } from './routes/online-arabic-language-classes'
import { Route as NooraniQaidaOnlineRouteImport } from './routes/noorani-qaida-online'
import { Route as FreeTrialRouteImport } from './routes/free-trial'
import { Route as FemaleQuranClassesOnlineRouteImport } from './routes/female-quran-classes-online'
import { Route as FeeScheduleRouteImport } from './routes/fee-schedule'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiTrialRouteImport } from './routes/api.trial'
import { Route as ApiContactRouteImport } from './routes/api.contact'

const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranClassesForNewMuslimsRoute =
  QuranClassesForNewMuslimsRouteImport.update({
    id: '/quran-classes-for-new-muslims',
    path: '/quran-classes-for-new-muslims',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineTajweedClassesRoute = OnlineTajweedClassesRouteImport.update({
  id: '/online-tajweed-classes',
  path: '/online-tajweed-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineQuranRecitationClassesRoute =
  OnlineQuranRecitationClassesRouteImport.update({
    id: '/online-quran-recitation-classes',
    path: '/online-quran-recitation-classes',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnlineQuranClassesUsaRoute = OnlineQuranClassesUsaRouteImport.update({
  id: '/online-quran-classes-usa',
  path: '/online-quran-classes-usa',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineQuranClassesUkRoute = OnlineQuranClassesUkRouteImport.update({
  id: '/online-quran-classes-uk',
  path: '/online-quran-classes-uk',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineQuranClassesForKidsRoute =
  OnlineQuranClassesForKidsRouteImport.update({
    id: '/online-quran-classes-for-kids',
    path: '/online-quran-classes-for-kids',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnlineQuranClassesForAdultsRoute =
  OnlineQuranClassesForAdultsRouteImport.update({
    id: '/online-quran-classes-for-adults',
    path: '/online-quran-classes-for-adults',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnlineQuranClassesCanadaRoute =
  OnlineQuranClassesCanadaRouteImport.update({
    id: '/online-quran-classes-canada',
    path: '/online-quran-classes-canada',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnlineQuranClassesAustraliaRoute =
  OnlineQuranClassesAustraliaRouteImport.update({
    id: '/online-quran-classes-australia',
    path: '/online-quran-classes-australia',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnlineIslamicStudiesRoute = OnlineIslamicStudiesRouteImport.update({
  id: '/online-islamic-studies',
  path: '/online-islamic-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineHifzClassesRoute = OnlineHifzClassesRouteImport.update({
  id: '/online-hifz-classes',
  path: '/online-hifz-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineArabicLanguageClassesRoute =
  OnlineArabicLanguageClassesRouteImport.update({
    id: '/online-arabic-language-classes',
    path: '/online-arabic-language-classes',
    getParentRoute: () => rootRouteImport,
  } as any)
const NooraniQaidaOnlineRoute = NooraniQaidaOnlineRouteImport.update({
  id: '/noorani-qaida-online',
  path: '/noorani-qaida-online',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeTrialRoute = FreeTrialRouteImport.update({
  id: '/free-trial',
  path: '/free-trial',
  getParentRoute: () => rootRouteImport,
} as any)
const FemaleQuranClassesOnlineRoute =
  FemaleQuranClassesOnlineRouteImport.update({
    id: '/female-quran-classes-online',
    path: '/female-quran-classes-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeeScheduleRoute = FeeScheduleRouteImport.update({
  id: '/fee-schedule',
  path: '/fee-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrialRoute = ApiTrialRouteImport.update({
  id: '/api/trial',
  path: '/api/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/fee-schedule': typeof FeeScheduleRoute
  '/female-quran-classes-online': typeof FemaleQuranClassesOnlineRoute
  '/free-trial': typeof FreeTrialRoute
  '/noorani-qaida-online': typeof NooraniQaidaOnlineRoute
  '/online-arabic-language-classes': typeof OnlineArabicLanguageClassesRoute
  '/online-hifz-classes': typeof OnlineHifzClassesRoute
  '/online-islamic-studies': typeof OnlineIslamicStudiesRoute
  '/online-quran-classes-australia': typeof OnlineQuranClassesAustraliaRoute
  '/online-quran-classes-canada': typeof OnlineQuranClassesCanadaRoute
  '/online-quran-classes-for-adults': typeof OnlineQuranClassesForAdultsRoute
  '/online-quran-classes-for-kids': typeof OnlineQuranClassesForKidsRoute
  '/online-quran-classes-uk': typeof OnlineQuranClassesUkRoute
  '/online-quran-classes-usa': typeof OnlineQuranClassesUsaRoute
  '/online-quran-recitation-classes': typeof OnlineQuranRecitationClassesRoute
  '/online-tajweed-classes': typeof OnlineTajweedClassesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quran-classes-for-new-muslims': typeof QuranClassesForNewMuslimsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/tutors': typeof TutorsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/trial': typeof ApiTrialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/fee-schedule': typeof FeeScheduleRoute
  '/female-quran-classes-online': typeof FemaleQuranClassesOnlineRoute
  '/free-trial': typeof FreeTrialRoute
  '/noorani-qaida-online': typeof NooraniQaidaOnlineRoute
  '/online-arabic-language-classes': typeof OnlineArabicLanguageClassesRoute
  '/online-hifz-classes': typeof OnlineHifzClassesRoute
  '/online-islamic-studies': typeof OnlineIslamicStudiesRoute
  '/online-quran-classes-australia': typeof OnlineQuranClassesAustraliaRoute
  '/online-quran-classes-canada': typeof OnlineQuranClassesCanadaRoute
  '/online-quran-classes-for-adults': typeof OnlineQuranClassesForAdultsRoute
  '/online-quran-classes-for-kids': typeof OnlineQuranClassesForKidsRoute
  '/online-quran-classes-uk': typeof OnlineQuranClassesUkRoute
  '/online-quran-classes-usa': typeof OnlineQuranClassesUsaRoute
  '/online-quran-recitation-classes': typeof OnlineQuranRecitationClassesRoute
  '/online-tajweed-classes': typeof OnlineTajweedClassesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quran-classes-for-new-muslims': typeof QuranClassesForNewMuslimsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/tutors': typeof TutorsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/trial': typeof ApiTrialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/fee-schedule': typeof FeeScheduleRoute
  '/female-quran-classes-online': typeof FemaleQuranClassesOnlineRoute
  '/free-trial': typeof FreeTrialRoute
  '/noorani-qaida-online': typeof NooraniQaidaOnlineRoute
  '/online-arabic-language-classes': typeof OnlineArabicLanguageClassesRoute
  '/online-hifz-classes': typeof OnlineHifzClassesRoute
  '/online-islamic-studies': typeof OnlineIslamicStudiesRoute
  '/online-quran-classes-australia': typeof OnlineQuranClassesAustraliaRoute
  '/online-quran-classes-canada': typeof OnlineQuranClassesCanadaRoute
  '/online-quran-classes-for-adults': typeof OnlineQuranClassesForAdultsRoute
  '/online-quran-classes-for-kids': typeof OnlineQuranClassesForKidsRoute
  '/online-quran-classes-uk': typeof OnlineQuranClassesUkRoute
  '/online-quran-classes-usa': typeof OnlineQuranClassesUsaRoute
  '/online-quran-recitation-classes': typeof OnlineQuranRecitationClassesRoute
  '/online-tajweed-classes': typeof OnlineTajweedClassesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quran-classes-for-new-muslims': typeof QuranClassesForNewMuslimsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/tutors': typeof TutorsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/trial': typeof ApiTrialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/fee-schedule'
    | '/female-quran-classes-online'
    | '/free-trial'
    | '/noorani-qaida-online'
    | '/online-arabic-language-classes'
    | '/online-hifz-classes'
    | '/online-islamic-studies'
    | '/online-quran-classes-australia'
    | '/online-quran-classes-canada'
    | '/online-quran-classes-for-adults'
    | '/online-quran-classes-for-kids'
    | '/online-quran-classes-uk'
    | '/online-quran-classes-usa'
    | '/online-quran-recitation-classes'
    | '/online-tajweed-classes'
    | '/privacy-policy'
    | '/quran-classes-for-new-muslims'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-conditions'
    | '/thank-you'
    | '/tutors'
    | '/api/contact'
    | '/api/trial'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/fee-schedule'
    | '/female-quran-classes-online'
    | '/free-trial'
    | '/noorani-qaida-online'
    | '/online-arabic-language-classes'
    | '/online-hifz-classes'
    | '/online-islamic-studies'
    | '/online-quran-classes-australia'
    | '/online-quran-classes-canada'
    | '/online-quran-classes-for-adults'
    | '/online-quran-classes-for-kids'
    | '/online-quran-classes-uk'
    | '/online-quran-classes-usa'
    | '/online-quran-recitation-classes'
    | '/online-tajweed-classes'
    | '/privacy-policy'
    | '/quran-classes-for-new-muslims'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-conditions'
    | '/thank-you'
    | '/tutors'
    | '/api/contact'
    | '/api/trial'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/fee-schedule'
    | '/female-quran-classes-online'
    | '/free-trial'
    | '/noorani-qaida-online'
    | '/online-arabic-language-classes'
    | '/online-hifz-classes'
    | '/online-islamic-studies'
    | '/online-quran-classes-australia'
    | '/online-quran-classes-canada'
    | '/online-quran-classes-for-adults'
    | '/online-quran-classes-for-kids'
    | '/online-quran-classes-uk'
    | '/online-quran-classes-usa'
    | '/online-quran-recitation-classes'
    | '/online-tajweed-classes'
    | '/privacy-policy'
    | '/quran-classes-for-new-muslims'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-conditions'
    | '/thank-you'
    | '/tutors'
    | '/api/contact'
    | '/api/trial'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  FeeScheduleRoute: typeof FeeScheduleRoute
  FemaleQuranClassesOnlineRoute: typeof FemaleQuranClassesOnlineRoute
  FreeTrialRoute: typeof FreeTrialRoute
  NooraniQaidaOnlineRoute: typeof NooraniQaidaOnlineRoute
  OnlineArabicLanguageClassesRoute: typeof OnlineArabicLanguageClassesRoute
  OnlineHifzClassesRoute: typeof OnlineHifzClassesRoute
  OnlineIslamicStudiesRoute: typeof OnlineIslamicStudiesRoute
  OnlineQuranClassesAustraliaRoute: typeof OnlineQuranClassesAustraliaRoute
  OnlineQuranClassesCanadaRoute: typeof OnlineQuranClassesCanadaRoute
  OnlineQuranClassesForAdultsRoute: typeof OnlineQuranClassesForAdultsRoute
  OnlineQuranClassesForKidsRoute: typeof OnlineQuranClassesForKidsRoute
  OnlineQuranClassesUkRoute: typeof OnlineQuranClassesUkRoute
  OnlineQuranClassesUsaRoute: typeof OnlineQuranClassesUsaRoute
  OnlineQuranRecitationClassesRoute: typeof OnlineQuranRecitationClassesRoute
  OnlineTajweedClassesRoute: typeof OnlineTajweedClassesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QuranClassesForNewMuslimsRoute: typeof QuranClassesForNewMuslimsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  ThankYouRoute: typeof ThankYouRoute
  TutorsRoute: typeof TutorsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiTrialRoute: typeof ApiTrialRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran-classes-for-new-muslims': {
      id: '/quran-classes-for-new-muslims'
      path: '/quran-classes-for-new-muslims'
      fullPath: '/quran-classes-for-new-muslims'
      preLoaderRoute: typeof QuranClassesForNewMuslimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-tajweed-classes': {
      id: '/online-tajweed-classes'
      path: '/online-tajweed-classes'
      fullPath: '/online-tajweed-classes'
      preLoaderRoute: typeof OnlineTajweedClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-quran-recitation-classes': {
      id: '/online-quran-recitation-classes'
      path: '/online-quran-recitation-classes'
      fullPath: '/online-quran-recitation-classes'
      preLoaderRoute: typeof OnlineQuranRecitationClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-quran-classes-usa': {
      id: '/online-quran-classes-usa'
      path: '/online-quran-classes-usa'
      fullPath: '/online-quran-classes-usa'
      preLoaderRoute: typeof OnlineQuranClassesUsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-quran-classes-uk': {
      id: '/online-quran-classes-uk'
      path: '/online-quran-classes-uk'
      fullPath: '/online-quran-classes-uk'
      preLoaderRoute: typeof OnlineQuranClassesUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-quran-classes-for-kids': {
      id: '/online-quran-classes-for-kids'
      path: '/online-quran-classes-for-kids'
      fullPath: '/online-quran-classes-for-kids'
      preLoaderRoute: typeof OnlineQuranClassesForKidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-quran-classes-for-adults': {
      id: '/online-quran-classes-for-adults'
      path: '/online-quran-classes-for-adults'
      fullPath: '/online-quran-classes-for-adults'
      preLoaderRoute: typeof OnlineQuranClassesForAdultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-quran-classes-canada': {
      id: '/online-quran-classes-canada'
      path: '/online-quran-classes-canada'
      fullPath: '/online-quran-classes-canada'
      preLoaderRoute: typeof OnlineQuranClassesCanadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-quran-classes-australia': {
      id: '/online-quran-classes-australia'
      path: '/online-quran-classes-australia'
      fullPath: '/online-quran-classes-australia'
      preLoaderRoute: typeof OnlineQuranClassesAustraliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-islamic-studies': {
      id: '/online-islamic-studies'
      path: '/online-islamic-studies'
      fullPath: '/online-islamic-studies'
      preLoaderRoute: typeof OnlineIslamicStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-hifz-classes': {
      id: '/online-hifz-classes'
      path: '/online-hifz-classes'
      fullPath: '/online-hifz-classes'
      preLoaderRoute: typeof OnlineHifzClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-arabic-language-classes': {
      id: '/online-arabic-language-classes'
      path: '/online-arabic-language-classes'
      fullPath: '/online-arabic-language-classes'
      preLoaderRoute: typeof OnlineArabicLanguageClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noorani-qaida-online': {
      id: '/noorani-qaida-online'
      path: '/noorani-qaida-online'
      fullPath: '/noorani-qaida-online'
      preLoaderRoute: typeof NooraniQaidaOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-trial': {
      id: '/free-trial'
      path: '/free-trial'
      fullPath: '/free-trial'
      preLoaderRoute: typeof FreeTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/female-quran-classes-online': {
      id: '/female-quran-classes-online'
      path: '/female-quran-classes-online'
      fullPath: '/female-quran-classes-online'
      preLoaderRoute: typeof FemaleQuranClassesOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-schedule': {
      id: '/fee-schedule'
      path: '/fee-schedule'
      fullPath: '/fee-schedule'
      preLoaderRoute: typeof FeeScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trial': {
      id: '/api/trial'
      path: '/api/trial'
      fullPath: '/api/trial'
      preLoaderRoute: typeof ApiTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  FeeScheduleRoute: FeeScheduleRoute,
  FemaleQuranClassesOnlineRoute: FemaleQuranClassesOnlineRoute,
  FreeTrialRoute: FreeTrialRoute,
  NooraniQaidaOnlineRoute: NooraniQaidaOnlineRoute,
  OnlineArabicLanguageClassesRoute: OnlineArabicLanguageClassesRoute,
  OnlineHifzClassesRoute: OnlineHifzClassesRoute,
  OnlineIslamicStudiesRoute: OnlineIslamicStudiesRoute,
  OnlineQuranClassesAustraliaRoute: OnlineQuranClassesAustraliaRoute,
  OnlineQuranClassesCanadaRoute: OnlineQuranClassesCanadaRoute,
  OnlineQuranClassesForAdultsRoute: OnlineQuranClassesForAdultsRoute,
  OnlineQuranClassesForKidsRoute: OnlineQuranClassesForKidsRoute,
  OnlineQuranClassesUkRoute: OnlineQuranClassesUkRoute,
  OnlineQuranClassesUsaRoute: OnlineQuranClassesUsaRoute,
  OnlineQuranRecitationClassesRoute: OnlineQuranRecitationClassesRoute,
  OnlineTajweedClassesRoute: OnlineTajweedClassesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QuranClassesForNewMuslimsRoute: QuranClassesForNewMuslimsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  ThankYouRoute: ThankYouRoute,
  TutorsRoute: TutorsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiTrialRoute: ApiTrialRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
